[MODEL_MISC]
init_file = "/glade/work/tienyiao/projects/CAM5_coupling/99_EMOM_dev/EMOM/tutorial/03_find_flux_correction/inputdata/EXAMPLE_EMOM.init.snapshot.jld2"
enable_archive = true
monthly_record = ["{ESSENTIAL}", "QFLXT", "QFLXS"]
rpointer_file = "rpointer.emom"
timetype = "DateTimeNoLeap"
daily_record = []

[DRIVER]
archive_root = "/glade/scratch/tienyiao/archive/EXAMPLE_EMOM"
casename = "EXAMPLE_EMOM"
caserun = "/glade/scratch/tienyiao/EXAMPLE_EMOM/run"
caseroot = "/glade/work/tienyiao/projects/CAM5_coupling/99_EMOM_dev/EMOM/tutorial/03_find_flux_correction/cases/EXAMPLE_EMOM"

[DOMAIN]
z_w_file = "/glade/work/tienyiao/projects/CAM5_coupling/99_EMOM_dev/EMOM/tutorial/03_find_flux_correction/inputdata/z_w.nc"
domain_file = "/glade/work/tienyiao/projects/CAM5_coupling/99_EMOM_dev/EMOM/tutorial/03_find_flux_correction/../../data/CESM_domains/domain.ocn.gx1v6.090206.nc"
Nz_bot_file = "/glade/work/tienyiao/projects/CAM5_coupling/99_EMOM_dev/EMOM/tutorial/03_find_flux_correction/inputdata/Nz_bot_EMOM.nc"

[MODEL_CORE]
MLD_scheme = "datastream"
Ekman_layers = 5
advection_scheme = "ekman_CO2012"
weak_restoring = "off"
cdata_align_time = "0001-01-01 00:00:00"
Qflx = "off"
cdata_end_time = "0002-01-01 00:00:00"
convective_adjustment = "on"
Returnflow_layers = 28
transform_vector_field = true
cdata_beg_time = "0001-01-01 00:00:00"
UVsfc_scheme = "datastream"
"τwk_SALT" = 3.1536e9
"τwk_TEMP" = 3.1536e9
substeps = 8
Qflx_finding = "on"

    [MODEL_CORE.cdata_var_file_map]
