[MODEL_MISC]
init_file = "/glade/work/tienyiao/projects/CAM5_coupling/99_EMOM_dev/EMOM/tools/generate_init_files/data/init_ocn.jld2"
enable_archive = true
monthly_record = ["{ESSENTIAL}", "QFLXT", "QFLXS"]
rpointer_file = "rpointer.emom"
daily_record = []

[DRIVER]
archive_list = "archive_list.txt"
archive_root = "/glade/work/tienyiao/projects/CAM5_coupling/99_EMOM_dev/EMOM/tools/generate_init_files/dummy/archive"
casename = "dummy"
caserun = "/glade/work/tienyiao/projects/CAM5_coupling/99_EMOM_dev/EMOM/tools/generate_init_files/dummy/caserun"
caseroot = "/glade/work/tienyiao/projects/CAM5_coupling/99_EMOM_dev/EMOM/tools/generate_init_files/dummy/caseroot"
compute_QFLX_direct_method = false

[DOMAIN]
z_w_file = "/glade/work/tienyiao/projects/CAM5_coupling/99_EMOM_dev/EMOM/tutorial/03_find_flux_correction/inputdata/z_w.nc"
domain_file = "/glade/work/tienyiao/projects/CAM5_coupling/99_EMOM_dev/EMOM/tutorial/03_find_flux_correction/../../data/CESM_domains/domain.ocn.gx1v6.090206.nc"
Nz_bot_file = "/glade/work/tienyiao/projects/CAM5_coupling/99_EMOM_dev/EMOM/tutorial/03_find_flux_correction/inputdata/Nz_bot_EMOM.nc"

[MODEL_CORE]
MLD_scheme = "static"
cdata_var_file_QFLXT = ""
substeps = 8
timetype = "DateTimeNoLeap"
"ϵ" = 1.4e-5
Ekman_layers = 3
Ks_H = 1000.0
advection_scheme = "ekman_AGA2020"
"rad_ζ1" = 0.15
weak_restoring = "off"
cdata_align_time = "0001-01-01 00:00:00"
Qflx = "off"
"τfrz" = 3600.0
cdata_end_time = "0002-01-01 00:00:00"
cdata_var_file_SALT = ""
Ks_V = 0.0001
convective_adjustment = "on"
Returnflow_layers = 7
cdata_var_file_QFLXS = ""
transform_vector_field = true
Ks_V_cva = 1.0
cdata_var_file_HMXL = ""
"rad_ζ2" = 23.0
rad_R = 0.58
cdata_beg_time = "0001-01-01 00:00:00"
"γ" = 0.06
"τwk_SALT" = 3.1536e10
"τwk_TEMP" = 3.1536e10
UVSFC_scheme = "static"
cdata_var_file_TEMP = ""
Qflx_finding = "off"
