[ env_run ]
    STOP_OPTION = "ndays"
    STOP_N = 5
    OCN_NCPL = 1
    DOCN_SOM_FILENAME = "pop_frc.gx3v7.110128.nc"
    OCN_TIGHT_COUPLING = "FALSE"


[ env_mach_pes ]

    NTASKS_ATM = 288
    NTHRDS_ATM =   1
    ROOTPE_ATM =   0

    NTASKS_LND = 288
    NTHRDS_LND =   1
    ROOTPE_LND =   0

    NTASKS_ICE = 288
    NTHRDS_ICE =   1
    ROOTPE_ICE =   0

    NTASKS_OCN = 256
    NTHRDS_OCN =   1
    ROOTPE_OCN =   0

    NTASKS_CPL = 288
    NTHRDS_CPL =   1
    ROOTPE_CPL =   0

    NTASKS_GLC = 288
    NTHRDS_GLC =   1
    ROOTPE_GLC =   0

    NTASKS_ROF = 288
    NTHRDS_ROF =   1
    ROOTPE_ROF =   0

    NTASKS_WAV = 288
    NTHRDS_WAV =   1
    ROOTPE_WAV =   0


