#PBS -A UMIA0022
#PBS -N EXAMPLE_EMOM
#PBS -q economy
#PBS -l select=9:ncpus=36:mpiprocs=36:ompthreads=1
#PBS -l walltime="12:00:00"
#PBS -j oe
#PBS -S /bin/bash

#!/bin/bash

bash /glade/work/tienyiao/projects/CAM5_coupling/21_EMOM/EMOM/example/01_CESM_B1850C5/cases/EXAMPLE_EMOM/EXAMPLE_EMOM.destroy_tunnel
/bin/csh /glade/work/tienyiao/projects/CAM5_coupling/21_EMOM/EMOM/example/01_CESM_B1850C5/cases/EXAMPLE_EMOM/EXAMPLE_EMOM.cesm.run &
/glade/work/tienyiao/projects/CAM5_coupling/21_EMOM/EMOM/example/01_CESM_B1850C5/cases/EXAMPLE_EMOM/EXAMPLE_EMOM.ocn.run &
wait

